version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    depends_on:
      - db

  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - app


# version: "3"
# services:
#   app:
#     build: ./app
#     links:
#       - db
#     ports:
#       - "5000:5000"
#     depends_on:
#       - db
#     command: bash -c "sleep 10 && python app.py"  # Add a delay of 10 seconds before starting the app

#   db:
#     image: mysql:5.7
#     ports:
#       - "32000:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#     volumes:
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#       - ./data:/var/lib/mysql

#   frontend:
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile
#     ports:
#       - "8501:8501"
#     depends_on:
#       - app

#   nginx:
#     build:
#       context: .
#       dockerfile: nginx/Dockerfile
#     ports:
#       - "80:80"
#       - "443:443"
#     depends_on:
#       - frontend
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#       - ./nginx/certificates:/etc/nginx/certificates
