version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql

  app:
    image: nat997/autodeployfromgithubtest:backend-latest
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    image: nat997/autodeployfromgithubtest:frontend-latest
    ports:
      - "8501:8501"
    depends_on:
      - app