version: '3'

services:
  mysql:
    image: nat997/deploycicd:mysql-v1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql

  app:
    image: nat997/deploycicd:app-v1
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    image: nat997/deploycicd:frontend-v1
    ports:
      - "80:80"
      - "443:443"