name: Build Frontend Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/autodeployfromgithubtest:frontend-latest -f frontend/Dockerfile .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/autodeployfromgithubtest:frontend-latest
