name: Streamlit FlaskAPI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install -r frontend/requirements.txt

      - name: Create and initialize database
        run: |
          mysql -h 127.0.0.1 -P 3307 -u root -proot -e "CREATE DATABASE IF NOT EXISTS labdata;"
          mysql -h 127.0.0.1 -P 3307 -u root -proot labdata < app/db/init.sql

      - name: Run Flask API tests
        working-directory: app
        run: pytest tests/

      - name: Run Streamlit app tests
        working-directory: frontend
        run: pytest tests/
