name: Streamlit Frontend Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set this to your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pandas numpy matplotlib requests

    - name: Run Streamlit in background
      run: |
        cd frontend
        streamlit run streamlitfrontapp.py --server.headless true --server.enableCORS false --server.port 8501 &
        sleep 10  # Allow some time for the server to start
        if ! pgrep -f streamlit; then
          echo "Streamlit app failed to start"
          exit 1
        fi
      timeout-minutes: 2
