name: Streamlit Frontend Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8' 

    - name: Install dependencies
      run: |
        pip install requests
        python -m pip install --upgrade pip
        pip install -r frontend/requirements.txt

    - name: Check Streamlit file
      run: |
        cd frontend
        streamlit run streamlitfrontapp.py --server.headless true --server.enableCORS false --server.port 8501

