name: Docker Compose Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      app:
        image: your-app-image:latest  # Replace with the image name of your app
        ports:
          - 5000:5000
        options: --health-cmd="curl -f http://localhost:5000/ || exit 1" --health-interval=10s --health-timeout=5s --health-retries=3

      db:
        image: mysql:8.0
        ports:
          - 32000:3306
        environment:
          MYSQL_ROOT_PASSWORD: root
        volumes:
          - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
          - ./data:/var/lib/mysql

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker Compose
        run: |
          docker-compose up -d --build
          docker-compose ps
        timeout-minutes: 5

      - name: Wait for services to be healthy
        run: |
          docker-compose ps
          while [[ "$(docker inspect -f '{{.State.Health.Status}}' <container-name-or-id>)" != "healthy" ]]; do
            echo "Waiting for services to be healthy..."
            sleep 10
          done
        timeout-minutes: 5

      - name: Run tests
        run: |
          # Replace with the command to run your tests
          docker-compose exec app pytest tests/
        timeout-minutes: 15

      - name: Stop and remove containers
        run: docker-compose down
