name: FlaskAPI TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.11.0
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'

      - name: Install dependencies
        run: |
          pip install requests
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run Flask API tests
        working-directory: app
        run: pytest test_app.py

