name: FlaskAPI TEST

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: Run Flask API tests
        working-directory: app
        run: pytest test_app.py

      - name: Run Flask API server on port 5000
        working-directory: app
        run: |
          PORT=5000 python app.py &
          # Store PID
          APP_PID=$!
          sleep 10
          if kill -0 $APP_PID 2>/dev/null; then
            echo "App is running successfully on port 5000"
            kill $APP_PID
          else
            echo "App failed to start or crashed"
            exit 1
          fi
